#!/bin/bash

# PolyHedge - Environment Setup Script
# This script helps you create a .env file with required variables

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║                 PolyHedge - Environment Setup Wizard                      ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""

# Check if .env already exists
if [ -f ".env" ]; then
    echo "⚠️  .env file already exists!"
    echo ""
    read -p "Do you want to overwrite it? (yes/NO): " overwrite
    if [ "$overwrite" != "yes" ]; then
        echo "Cancelled. Existing .env file kept."
        exit 0
    fi
    echo ""
fi

echo "This wizard will help you create a .env file with required configuration."
echo ""
echo "⚠️  SECURITY WARNING:"
echo "    • Use a separate deployer account (not your main wallet)"
echo "    • Never share your private keys"
echo "    • Never commit .env file to git"
echo ""
read -p "Press Enter to continue..."
echo ""

# Create .env file
cat > .env << 'ENVFILE'
# PolyHedge Environment Configuration
# Generated by setup-env.sh
# NEVER commit this file to git!

# ==============================================================================
# DEPLOYER PRIVATE KEY
# ==============================================================================
ENVFILE

echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo "1. DEPLOYER PRIVATE KEY"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "Enter your deployer wallet private key (without 0x prefix)"
echo "⚠️  Use a SEPARATE account, not your main wallet!"
echo ""
read -sp "Private Key: " private_key
echo ""

if [ -z "$private_key" ]; then
    echo "❌ Private key cannot be empty!"
    exit 1
fi

echo "__RUNTIME_DEPLOYER_PRIVATE_KEY=$private_key" >> .env
echo "" >> .env

echo ""
echo "✅ Private key saved"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo "2. ALCHEMY API KEY"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "Get from: https://www.alchemy.com/"
echo "Create app → Select Arbitrum → Copy API key"
echo ""
read -p "Alchemy API Key: " alchemy_key

if [ -z "$alchemy_key" ]; then
    echo "❌ Alchemy API key cannot be empty!"
    exit 1
fi

cat >> .env << ENVFILE
# ==============================================================================
# ALCHEMY API KEY
# ==============================================================================
ALCHEMY_API_KEY=$alchemy_key

ENVFILE

echo ""
echo "✅ Alchemy API key saved"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo "3. ARBISCAN API KEY"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "Get from: https://arbiscan.io/myapikey"
echo "Sign up → Create API key → Copy key"
echo ""
read -p "Arbiscan API Key: " arbiscan_key

if [ -z "$arbiscan_key" ]; then
    echo "⚠️  Warning: Verification will not work without Arbiscan API key"
    echo "You can add it later by editing .env file"
else
    cat >> .env << ENVFILE
# ==============================================================================
# ARBISCAN API KEY
# ==============================================================================
ETHERSCAN_V2_API_KEY=$arbiscan_key

ENVFILE
    echo ""
    echo "✅ Arbiscan API key saved"
fi

# Add remaining configuration
cat >> .env << 'ENVFILE'

# ==============================================================================
# PRE-CONFIGURED ADDRESSES (Arbitrum Mainnet)
# ==============================================================================
USDC_ADDRESS=0xaf88d065e77c8cC2239327C5EDb3A432268e5831

# ==============================================================================
# DEPLOYED CONTRACT ADDRESSES (Fill after deployment)
# ==============================================================================
# STRATEGY_MANAGER_ADDRESS=
# HEDGE_EXECUTOR_ADDRESS=
ENVFILE

echo ""
echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║                        ✅ .env FILE CREATED!                               ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "Your .env file has been created with:"
echo "  ✅ Deployer private key"
echo "  ✅ Alchemy API key"
if [ ! -z "$arbiscan_key" ]; then
    echo "  ✅ Arbiscan API key"
else
    echo "  ⚠️  Arbiscan API key (missing - add later)"
fi
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo "NEXT STEPS:"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "1. Fund your deployer account with 0.05+ ETH on Arbitrum mainnet"
echo "   Bridge: https://bridge.arbitrum.io/"
echo ""
echo "2. Test on testnet first (RECOMMENDED!):"
echo "   cd packages/hardhat"
echo "   yarn hardhat deploy --network arbitrumSepolia"
echo ""
echo "3. Deploy to mainnet:"
echo "   ./deploy-mainnet.sh"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""

